backend:
  name: github
  repo: turinproject/plugins-repository

media_folder: static/assets
public_folder: assets

collections:
  - name: plugins
    label: "Plugins"
    folder: "content/plugins/submitted"
    create: true
    fields:
      - {label: "Github Username", name: "username", widget: "string"}
      - {label: "Repository URL", name: "gitrepo", widget: "string"}
      - {label: "Readme.md", name: "readme", widget: "file"}