backend:
  name: git-gateway
  repo: turinproject/plugins-repository

media_folder: static/assets
public_folder: assets

collections:
  - name: plugins
    label: "Plugins"
    folder: "content/plugins/submitted"
    create: true
    fields:
      - {label: "Plugin Name", name: "title", widget: "string"}
      - {label: "Last Updated", name: "date", widget: "datetime"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Plugin Type", name: "category", widget: "select", options: ["Generators", "Commands", "Data", "Force Fields"]}
      - {label: "Keywords", name: "tags", widget: "list"}
      - {label: "Description", name: "body", widget: "markdown"}
